import './03-authentification/authentification.cy.ts'
import './04-profile/profile.cy.ts'
import './05-profile follow/followProfile.cy.ts'
import './06-group/createGroup.cy.ts'
import './07-group follow/followGroup.cy'
import './08-group membership/groupMembership.cy'
import './09-chat/chat.cy'
import './09-chat/chat.Group.cy'
import './10-search/search.cy.ts'
