-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

ALTER TABLE IF EXISTS public.profiles
    ADD COLUMN about text COLLATE pg_catalog."default";

ALTER TABLE IF EXISTS public.profiles
    ADD COLUMN city text COLLATE pg_catalog."default";

ALTER TABLE IF EXISTS public.profiles
    ADD COLUMN "contactEmail" text COLLATE pg_catalog."default";

ALTER TABLE IF EXISTS public.profiles
    ADD COLUMN "contactPhone" text COLLATE pg_catalog."default";

COMMENT ON COLUMN public.profiles."contactPhone"
    IS 'phone number can be used to contact person';

ALTER TABLE IF EXISTS public.profiles
    ADD COLUMN "postCode" integer;

ALTER TABLE IF EXISTS public.profiles
    ADD COLUMN street text COLLATE pg_catalog."default";
