-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.


/* ALTER TABLE IF EXISTS public.profiles
    ADD COLUMN "amendment_counter" bigint NOT NULL DEFAULT '0'::bigint;

ALTER TABLE IF EXISTS public.profiles
    ADD COLUMN "follower_counter" bigint NOT NULL DEFAULT '0'::bigint;

ALTER TABLE IF EXISTS public.profiles
    ADD COLUMN "following_counter" bigint NOT NULL DEFAULT '0'::bigint;

ALTER TABLE IF EXISTS public.profiles
    ADD COLUMN "groups_counter" bigint NOT NULL DEFAULT '0'::bigint;
 */

-- **********************
-- ******New Table*******
-- **********************

