name: Deploy Migrations to Staging

  
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN_STAGING }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_STAGING_DB_PASSWORD }}
      STAGING_PROJECT_ID: ${{ secrets.SUPABASE_STAGING_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: 1.6.0

      - run: |
          supabase link --project-ref $STAGING_PROJECT_ID -p $SUPABASE_STAGING_DB_PASSWORD
          supabase db push
